### PR TITLE
fix: high memory consumption issue

### PR DESCRIPTION
**Pull request by qjerome**
PR attempting at fixing issue #92
During the investigation of this issue, many other issues where encountered while running kunai under intensive load.
The fixes to the discovered issues got also addressed in this PR.

This PR consists in:
- a more appropriate cleanup of the tasks HashMap
- fixing a bug in command line parsing in Buffer::to_argv
- a better mnt namespace grooming
- a fix of file descriptor exhaustion due to bad fd management in code retrieving ebpf programs
- an update of `lru-st` crate

### CODE REVIEW

**Comment by qjerome** [comment]
Hey @miyoyo !
Sorry it took me a while to seriously look at this ... I got stuck in other implementations !
Would you have a bit of time to test that out ?

**Comment by miyoyo** [comment]
Hey @qjerome,

Thanks, it's already much better!

Testing it with regular loads, it seems to have much more consistent RAM usage.

However, I'm currently testing it with 4 terminals running
`while true; do podman run --rm -it alpine sleep 0.1; done`
(To saturate the buffer)

And memory usage is still creeping up _even though_ I'm hitting the max buffer size limit, I'll do another memory trace asap.

**Comment by qjerome** [comment]
@miyoyo I fixed minor stuffs in the way the cleanup occurs, it might improve a bit. Looking forward to seeing the output of your new load test ;). Thanks for doing that BTW

**Comment by miyoyo** [comment]
So, this is before your latest commit, but it appears that there are 3 things which use the most ram still:
- BytesMut, being expanded by Aya, consumes 40MB on a 6 core machine, which **does not match up** with your math in the associated ticket (1024 x 3320 x 8 = 27197440 B (~27 MB).)
- handle_correlation_event's hashmap consumes 6.6MB
- ...to_argv in https://github.com/kunai-project/kunai/blob/87eea6a853731b72df7ff676d259e4ebabafb040/kunai-common/src/buffer/user.rs#L10 ? This is **13.1 MB**

I used the podman commandline above, and let kunai "cool down" for a minute before kill -9'ing it.

[heaptrack.kunai.293629.zst.zip](https://github.com/user-attachments/files/16907502/heaptrack.kunai.293629.zst.zip)

**Comment by qjerome** [comment]
What profile are you compiling kunai with (release, debug, custom) ?

**Comment by miyoyo** [comment]
> What profile are you compiling kunai with (release, debug, custom) ?

To get profiling tools working, debug, although I don't notice remarkable differences between memory activity in either modes.

**Comment by miyoyo** [comment]
Memory raises more slowly with the latest commit, however it still raises, the only notable change I can see, is that now, Encoded_Event::from_bytes shows up in the memory breakdown:
- Aya's bytesmut abuse: 40MB
- Encoded_Event::from_bytes: 12.5MB
- HashMap: 6.6MB (this one seems constant)
- Buffer::to_argv: 17.5MB

I may want to run kunai overnight to see if only a few things grow, or if it's just a few specific elements.

**Comment by qjerome** [comment]
The good news is that I can now understand why Aya bytes mut takes 40MB. I did a bad calculation previously and now I find exactly 40MB.

All this can be explained because Aya's PerfEvent array expects a number of pages to be a power of 2, see: https://github.com/aya-rs/aya/blob/635ed3baed5442c1364a360d7234b72c4ffe3fd8/aya/src/maps/perf/perf_buffer.rs#L100
I don't really understand why but there is probably a good reason, I'm gonna ask in the Aya Discord channel.

So the size of the shared memory between user and kernel land is given by: `((max_event_size * n_events) / page_size).next_power_of_two() * page_size * n_cpus`.

Concretely it means, that for `max_buffered_events` == 1024 and `max_event_size` == 3320 and `page_size` == 4096  and `n_cpus` == 6 you get exactly 40MB ... So not much we can do for this I guess ! Unless this power of two check in Aya code can be removed.

**Comment by miyoyo** [comment]
I'll leave it to run for 2 hours, hopefully we can see if there's a cap on memory usage that comes in really late, or some things just roll down the hill over time.

**Comment by qjerome** [comment]
Those numbers are accumulated allocs, right ? This is not the amount of memory taken by Kunai ? Is it ?

**Comment by miyoyo** [comment]
> Those numbers are accumulated allocs, right ? This is not the amount of memory taken by Kunai ? Is it ?

This is the RSS as reported by linux, taken by the kunai process.

**Comment by qjerome** [comment]
OK, so there is probably another structure growing indefinitely somewhere !

**Comment by qjerome** [comment]
So apparently this power of 2 has a reason of existence, it is something required by the Kernel. According to Aya folks, I should use a RingBuffer for a more efficient event passing structure. 
The only issue that I have with RingBuffer is that it is available only since kernel 5.8 ... which break my compatibility with kernel older than 5.8. So I would need to manage both the cases ... which will increase code complexity and take time to implement.

I'll probably do this move, I don't know when though !

**Comment by miyoyo** [comment]
Alright, so, Aya clearly stops at 40MB, it's not the issue.

The Encoded_Event::from_bytes is also 12MB, not a problem.

The HashMap **DID** grow, it's 26.3MB, and will likely keep growing forever, as I don't think events are ever deleted from it.

The biggest one, though, is the user buffer string vector returned by to_argv:
https://github.com/kunai-project/kunai/blob/87eea6a853731b72df7ff676d259e4ebabafb040/kunai-common/src/buffer/user.rs#L10

My guess is that the hashmap keeps a reference to it _forever_, and, since the hashmap doesn't get smaller, you're basically accumulating strings forever.

**Comment by qjerome** [comment]
The HashMap shouldn't keep growing forever, it is supposed to clean entries on task exit ! At least that's what I implemented in the last 2 commits.

**Comment by miyoyo** [comment]
> The HashMap shouldn't keep growing forever, it is supposed to clean entries on task exit ! At least that's what I implemented in the last 2 commits.

I'm fairly certain I have the latest commit, as I did a cargo clean, pulled the files, manually verified they were correct, then built the lot, I can try again, if you'd like.

**Comment by qjerome** [comment]
I was not trying to say you did something wrong I rather assumed my fix isn't totally working.
I have another question though ! As you said you tried to saturate the number of events, do you get a lot of event being lost messages ?

**Comment by miyoyo** [comment]
A few at the start, but they slowly stop over time, I'll run it for another hour with a single podman event generator loop instead of 4, that does not saturate the events last I checked

**Comment by qjerome** [comment]
Ok, because any `exit` event lost will prevent the HashMap to cleanup properly, that is why I'm asking

**Comment by miyoyo** [comment]
Aya only used 5.2MB, the event producer is the bigger ram user with 18 MB.
The hashmap is 13.2 MB, so it's growing still (as far as I know)
The to_argv is huge, at 47 MB, so I think It may be that too.

**Comment by qjerome** [comment]
Hey @miyoyo,

I tried to instrument kunai with `heaptrack` and I notice RSS memory literally explodes as you noticed ... However this is a behavior I don't manage to replicate when I don't instrument with `heaptrack`, this is kind of weird but I think `heaptrack` might have so side effects ! Can you confirm on your side ?

**Comment by miyoyo** [comment]
> Hey @miyoyo,
> 
> I tried to instrument kunai with `heaptrack` and I notice RSS memory literally explodes as you noticed ... However this is a behavior I don't manage to replicate when I don't instrument with `heaptrack`, this is kind of weird but I think `heaptrack` might have so side effects ! Can you confirm on your side ?
> 
> Without instrumentation RSS memory keeps steady around 90MB while after some seconds it reaches 150MB when instrumented with heaptrack ...
> 
> NB: I used a `dev-opt` build which compiles Kunai with Rust debugging information but the code gets optimized

Heaptrack does consume some RAM, but it does not prevent rust from cleaning up memory, the leak exists regardless of it.

I let kunai run without heaptrack for about 7 realtime hours (1h 15m CPU time), it's sitting at 852MB of RAM used right now.

**Comment by qjerome** [comment]
FYI @miyoyo, I fixed a bug in `to_argv` ... Very likely leading to a memory leak ! Yet I don't think this will solve all issues.

**Comment by qjerome** [comment]
Since I fixed this, it looks much more stable on my end !

**Comment by miyoyo** [comment]
It does look way more stable! I'll run it with heaptrack for a few hours.

**Comment by miyoyo** [comment]
Okay, so, while it does raise slower, it still is going up over time (140MB after 1h 15m)
Of which the two biggest contributors are _still_ the hashmap and to_argv.

So it is a better implementation, but still not a solution.

I wonder, is the hashmap _really_ being cleaned up? Because it's, as far as I can tell, the one thing that keeps a reference to the returned string from to_argv, and it's also bloating over time. (My previous 3 hour run reached 255MB of RAM used, of which 150MB were the string from to_argv, and 52.7 were  the hashmap)

**Comment by qjerome** [comment]
Indeed the hashmap keeps growing ... Yet I don't know the reason

**Comment by qjerome** [comment]
I think I understand the issue, very likely the way `exit_group` does the cleanup of the hashmap.

**Comment by miyoyo** [comment]
> I think I understand the issue, very likely the way `exit_group` does the cleanup of the hashmap.

I'll join you on that idea, I added some debug for insert/removal, and it seems that there's twice as much insertion than removal:

[2024-09-09T13:19:35Z WARN  kunai] Exited task count: 0 - Task Capacity: 448 - Task total added: 33
[2024-09-09T13:19:57Z WARN  kunai] Exited task count: 1000 - Task Capacity: 1792 - Task total added: 2109
[2024-09-09T13:20:30Z WARN  kunai] Exited task count: 2000 - Task Capacity: 1780 - Task total added: 4202
[2024-09-09T13:21:03Z WARN  kunai] Exited task count: 3000 - Task Capacity: 3584 - Task total added: 6295
[2024-09-09T13:21:36Z WARN  kunai] Exited task count: 4000 - Task Capacity: 3579 - Task total added: 8387
[2024-09-09T13:22:06Z WARN  kunai] Exited task count: 5000 - Task Capacity: 3558 - Task total added: 10477
[2024-09-09T13:22:36Z WARN  kunai] Exited task count: 6000 - Task Capacity: 3520 - Task total added: 12566
[2024-09-09T13:23:05Z WARN  kunai] Exited task count: 7000 - Task Capacity: 7168 - Task total added: 14656
[2024-09-09T13:23:36Z WARN  kunai] Exited task count: 8000 - Task Capacity: 7165 - Task total added: 16746
[2024-09-09T13:24:06Z WARN  kunai] Exited task count: 9000 - Task Capacity: 7151 - Task total added: 18835
[2024-09-09T13:24:37Z WARN  kunai] Exited task count: 10000 - Task Capacity: 7130 - Task total added: 20928

These are `self.exited_tasks`, `self.tasks.capacity()`, `self.added_tasks`

Added tasks counts everytime a task insert is attempted, and the map does not contain the task key.

**Comment by qjerome** [comment]
This is what I did too ;)
Gonna create a new eBPF probe that captures `task_free` to make a proper cleanup.

**Comment by qjerome** [comment]
Hey @miyoyo !
Latest commit should solve most of the issues (I hope).
FYI: `task_free` was not a good solution as it was implying modifying too much code for too little benefit (again some edge cases to deal with).

**Comment by qjerome** [comment]
Running now the stuff for several hours (under moderate load) and RSS seems to be bounded to 106 MB, for my specific case with PAGE_SIZE=4096 and 8 CPUs.

**Comment by qjerome** [comment]
@miyoyo, I tested all this on my side and the issue seems fixed (according to what I observed).
I would have liked your input on this, as you opened the issue but if you don't have time just tell me and I'll merge without your feedback.

**Comment by qjerome** [comment]
Merging the branch but not yet closing the issue. @miyoyo feel free to continue the discussion here or in the issue

**Pull request merged**
